"""essage=Добавил 6 дат

Revision ID: 08cfaa16b5fa
Revises: c34efae3d958
Create Date: 2023-06-09 13:53:45.461395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08cfaa16b5fa'
down_revision = 'c34efae3d958'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date1', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('date2', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('date3', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('date4', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('date5', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('date6', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date6')
    op.drop_column('users', 'date5')
    op.drop_column('users', 'date4')
    op.drop_column('users', 'date3')
    op.drop_column('users', 'date2')
    op.drop_column('users', 'date1')
    # ### end Alembic commands ###
