"""essage=menu

Revision ID: 455f990ce86d
Revises: aa6f2bf9f662
Create Date: 2023-06-09 17:44:41.744159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455f990ce86d'
down_revision = 'aa6f2bf9f662'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
