"""essage=Cascade

Revision ID: 4d1389325d2d
Revises: fb451bdcf0ee
Create Date: 2023-09-14 18:29:35.831649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d1389325d2d'
down_revision = 'fb451bdcf0ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('history_user_id_fkey', 'history', type_='foreignkey')
    op.create_foreign_key(None, 'history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('menu_items_parent_id_fkey', 'menu_items', type_='foreignkey')
    op.create_foreign_key(None, 'menu_items', 'menu_items', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    op.create_foreign_key('menu_items_parent_id_fkey', 'menu_items', 'menu_items', ['parent_id'], ['id'])
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.create_foreign_key('history_user_id_fkey', 'history', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
