"""essage=Добавил date_comment к User

Revision ID: 6800e54540eb
Revises: 689917b61f18
Create Date: 2023-06-13 10:19:45.579488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6800e54540eb'
down_revision = '689917b61f18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date1_comment', sa.String(length=2000), nullable=True))
    op.add_column('users', sa.Column('date2_comment', sa.String(length=2000), nullable=True))
    op.add_column('users', sa.Column('date3_comment', sa.String(length=2000), nullable=True))
    op.add_column('users', sa.Column('date4_comment', sa.String(length=2000), nullable=True))
    op.add_column('users', sa.Column('date5_comment', sa.String(length=2000), nullable=True))
    op.add_column('users', sa.Column('date6_comment', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date6_comment')
    op.drop_column('users', 'date5_comment')
    op.drop_column('users', 'date4_comment')
    op.drop_column('users', 'date3_comment')
    op.drop_column('users', 'date2_comment')
    op.drop_column('users', 'date1_comment')
    # ### end Alembic commands ###
