"""essage=index

Revision ID: 889403579ba5
Revises: 455f990ce86d
Create Date: 2023-06-09 18:18:49.587143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889403579ba5'
down_revision = '455f990ce86d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('index', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'index')
    # ### end Alembic commands ###
