"""essage=Дата

Revision ID: aa6f2bf9f662
Revises: 08cfaa16b5fa
Create Date: 2023-06-09 14:12:34.137902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa6f2bf9f662'
down_revision = '08cfaa16b5fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
